### ISSUE TITLE
/check_rabbitmq -a queues_count in v 3.6.12

### ISSUE THREAD

**Issue by pulsejets** [CaptPhunkosis/check_rabbitmq#16]
/usr/lib/nagios/plugins/check_rabbitmq -a queues_count -W 800 -C 1000
CRITICAL - list index out of range

added -q option  , du to header info resolving in multidimensional array
 def list_queues(cls):
        args = shlex.split('rabbitmqctl list_queues -q')

**Comment by drscream** [comment]
I think that is already fixed with the latest version and additional to that with the following pull request which is merged: https://github.com/CaptPhunkosis/check_rabbitmq/pull/17

**Comment by CaptPhunkosis** [comment]
Thanks!
